### PR TITLE
Custom framework applied to a webpage review

### PR DESCRIPTION
**Pull request by majovanilla**
In this project you will find:

- [ ] CSS file with the custom framework (main.css)

- [ ] CSS file with website styling (style.css)

- [ ] Linters file with corrections

- [ ] HTML checking

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
## Hi @majovainilla  and @euqueme :wave:  
### I like the effort you have put on this project!
The cloned site looks great!
Let's fix one issue before we mark this as complete
**[REQUIRED]** 
* We have some errors in your css file. Upload your code to http://jigsaw.w3.org/css-validator/validator and correct all the errors.

**After making the changes, submit another request for review** 

_Reviewed by `Simon Wathigo`
Happy Coding :computer:_

**Review by Forison — COMMENTED** [review]
# pull request under review By Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# 👏 Good Job Team👏
your project looks awesome and well-executed 👏👏. I like your file organization. Your readme is also very nice descriptive.👏👏
Let us do these changes to make our project💪 
* [x] Let us  activate stickler on the repo🙂
> visit (stickler-ci.com)[stickler-ci.com], login with your Github. Search your repo and activate the stickler on that repo.🙂

* [x] There is a horizontal scroll at xs, let us rectify this in other to make our project flawless🙂
Screenshot from 2019-10-15 16-05-38

* [x] let us fix the warning returned by the[ validator ](https://validator.w3.org)after uploading the index file.🙂


## Kindly do these changes and submit for review🙂

feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. i would be happy to assist you.
Happy coding😇

**Review by stratospherique — APPROVED** [review]
> ### Review by Ahmed Mahfoudh TSE

### Great job implementing the suggested changes :clap: . Congrats, your project is approved :heavy_check_mark:  and you may merge to master :+1: :+1:

**Pull request merged**
